on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Android Release

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.vars.outputs.tag }}
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  build_release:
    name: Build release
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create .env
        run: |
          echo "TOKEN_ENCODED=$TOKEN_ENCODED" > dotenv
        shell: bash
        env:
          TOKEN_ENCODED: ${{ secrets.TOKEN_ENCODED }}
      - name: Setup Java11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get flutter dependencies
        run: flutter pub get
      - name: Check format of dart code
        run: flutter format --set-exit-if-changed .
      - name: Statically analyse dart code
        run: flutter analyze .
      - name: Run widget tests
        run: flutter test
      - name: Build apk
        run: flutter build apk
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/apk/release/app-release.apk
          asset_name: NationalUniversityBuses.apk
          asset_content_type: application/octet-stream
